// design-sync entry: module facade over the repo's real zero-build DS code.
// Import order is load-bearing (mirrors index.html's script order):
//   1. react-globals — puts React/ReactDOM on window
//   2. fm-shim       — the FramerMotion shim extracted from index.html
//                      (regenerated by extract-html-assets.mjs; reads window.React)
//   3. shared.jsx    — the REAL design-system source, unmodified; it populates
//                      window with every component via Object.assign(window, …)
// The exports below re-surface those window globals as module exports.
// BgColorSystem is deliberately not exported: it renders null (it only pokes
// the site's background canvas) — nothing for a design to use.
import './react-globals.mjs';
import '../.cache/fm-shim.js';
import '../../shared.jsx';

const w = /** @type {any} */ (window);

// ── Brand ──
export const Wordmark = w.Wordmark;
export const LogoMark = w.LogoMark;

// ── Typography / display ──
export const SectionHeading = w.SectionHeading;
export const SectionBadge = w.SectionBadge;
export const BlurText = w.BlurText;
export const TypeText = w.TypeText;

// ── Controls ──
export const GlassBtn = w.GlassBtn;

// ── Navigation ──
export const Navbar = w.Navbar;
export const FooterBar = w.FooterBar;

// ── Effects ──
export const FadeTop = w.FadeTop;
export const FadeBottom = w.FadeBottom;

// ── Icons ──
export const ArrowUpRight = w.ArrowUpRight;
export const Play = w.Play;
export const Zap = w.Zap;
export const Palette = w.Palette;
export const BarChart3 = w.BarChart3;
export const Shield = w.Shield;
export const Check = w.Check;
export const Star = w.Star;
export const ChevronRight = w.ChevronRight;
export const ChevronDown = w.ChevronDown;
export const Users = w.Users;
export const BookOpen = w.BookOpen;
export const GitBranch = w.GitBranch;
export const Code2 = w.Code2;
export const Cpu = w.Cpu;
export const Layers = w.Layers;
export const Server = w.Server;
export const Globe = w.Globe;
export const Brain = w.Brain;
export const Award = w.Award;
export const Clock = w.Clock;
export const MessageSquare = w.MessageSquare;
export const TrendingUp = w.TrendingUp;
export const Sparkles = w.Sparkles;
export const Network = w.Network;
export const Workflow = w.Workflow;
export const MonitorPlay = w.MonitorPlay;
export const X = w.X;
export const Menu = w.Menu;
export const Info = w.Info;

// ── Non-component utilities (bundle API, excluded from the component list) ──
export const ACCENT = w.ACCENT;
export const ACCENT_RGB = w.ACCENT_RGB;
export const motion = w.motion;
export const AnimatePresence = w.AnimatePresence;
export const useInView = w.useInView;
export const tiltHandlers = w.tiltHandlers;
